version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Painel de gerenciamento
      - "25672:25672" # Comunicação de cluster
      - "4369:4369"   # EPMD
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq # Volume de persistência
    restart: always
